# Project Name
TARGET = screen_test # REPLACE THIS WITH THE FOLDER'S NAME

# Sources
CPP_SOURCES = main.cpp # add any other created source files here like libraries or classes or functions or whatever

# Library Locations, probably dont delete these but do add more if needed
LIBDAISY_DIR = ../DaisyExamples/libDaisy
DAISYSP_DIR = ../DaisyExamples/DaisySP

# Core location and generic Makefile, also wouldn't recommend deleting this either
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

